### ISSUE TITLE
PO file importer: How to structure translations in library and applications

### ISSUE THREAD

**Issue by MarcVanDaele90** [marcglasberg/i18n_extension#109]
I have both a library project/package which has some translations and an application (using this library) that also has translations.
The directory structure looks roughly like this
- Library/
  - lib/
  - assets/locales/*.po
- App/
  - lib/main.dart
  - assets/locales/*.po

Both the library project and the app project have a 
```
  static Future<void> loadTranslations() async {
    translations +=
    await GettextImporter().fromAssetDirectory("assets/locales");
    print("i18n: translation = $translations");
  }

```
but when calling the loadTranslations of the Library, it seems to read the *.po files from the assets/locales directory of the App.  
How can I indicate hat it should read from the "assets/locales" directory of the library project?

Do you have a fix for my setup or suggestions on how to improve my setup?
For example, is it somehow possible to indicate the package when loading assets? Similar to Image.asset() which has a package property.
Also loading `GettextImporter().fromAssetDirectory("packages/<library package name>/assets/locales");` seems to have no effect

**Comment by MarcVanDaele90** [comment]
Sorry, using `GettextImporter().fromAssetDirectory("packages/<library package name>/assets/locales")` does work.
If you happen to have suggestions to improve this setup, please let me know.  Otherwise, feel free to close this issue.

**Comment by marcglasberg** [comment]
The gettext importer is contributed by @bauerj 
Maybe he can help you.

**Comment by marcglasberg** [comment]
Version [14.0.0-dev.3] provides a new way to load translations from a file. See the CHANGELOG and the README:

* **Load translations from files**. If you want to load translations from files in your
  assets directory, create a folder and add some translation files like this:

  ```
  assets
  └── translations
      ├── en-US.json
      ├── es-ES.json
      ├── zh-Hans-CN.json
      └── pt.json 
  ```

  Don't forget to declare your assets directory in your `pubspec.yaml`:

  ```yaml
  flutter:
    assets:
      - assets/translations/
  ```

  Then, you can load the translations using `Translations.byFile()`:

  ```dart
  extension MyTranslations on String {
    static final _t = Translations.byFile('en-US', dir: 'assets/translations');     
    String get i18n => localize(this, _t);  
  }
  ```

  The above code will asynchronously load all the translations from the `.json` files
  present in the `assets/translations` directory, and then rebuild your widgets with
  those new translations.

  Note: Since rebuilding widgets when the translations finish loading can cause a visible
  flicker, you can optionally avoid that by preloading the translations before running
  your app. To that end, first create a `load()` method in your `MyTranslations`
  extension:

  ```dart
  extension MyTranslations on String {
    static final _t = Translations.byFile('en-US', dir: 'assets/translations');  
    String get i18n => localize(this, _t);  
    
    static Future<void> load() => _t.load(); // Here!  
  }
  ```

  And then, in your `main()` method, call `MyTranslations.load()` before running the app:

  ```dart
  void main() async {
    WidgetsFlutterBinding.ensureInitialized();
    
    await MyTranslations.load(); // Here!
    
    runApp(
      I18n(
        initialLocale: await I18n.loadLocale(),
        autoSaveLocale: true,
        child: AppCore(),
      ),
    );
  }
  ```

  Another alternative is using a `FutureBuilder`:

  ```dart
  return FutureBuilder(
    future: MyTranslations.load(),
    builder: (context, snapshot) {
      if (snapshot.connectionState == ConnectionState.done) {
      return MyWidget(...);
    } else {
      return const Center(child: CircularProgressIndicator());
    } ...
  ```       

  Try running
  the <a href="https://github.com/marcglasberg/i18n_extension/blob/master/example/lib/6_load_example/main.dart">
  load example</a>.
