### ISSUE TITLE
Localize app name (launcher name)

### ISSUE THREAD

**Issue by deadsoul44** [marcglasberg/i18n_extension#12]
Hello,

Thanks for the great library. Does it support app/launcher name localization? If not, is it possible to add this new feature?

**Comment by marcglasberg** [comment]
I wouldn't know what needs to be done to achieve that. Could you explain it to me in more detail?

**Comment by deadsoul44** [comment]
For example, the following package is used to change launcher name:

https://pub.dev/packages/flutter_launcher_name

And the following answer describes how to localize the app name:
https://stackoverflow.com/questions/5551939/how-to-change-the-name-of-application-in-launcher-in-android-according-to-the-la

**Comment by marcglasberg** [comment]
As far as I understand, the launcher name must be fixed in the AndroidManifest.xml (for Android) and Info.plist (for iOS). These are NOT Dart files. The flutter_launcher_name package is just a command-line tool to change these files for you. 

So it can't be done dynamically from inside the Dart code, which I understand is what you want i18n_extension to do. Sorry!
