### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY when running a test

### ISSUE THREAD

**Issue by MLZ91** [marcglasberg/i18n_extension#128]
When I try to run a testWidgets test I get the following exception:
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═════════════════════════════
The following UnsupportedError was thrown building _InheritedI18n:
Unsupported operation: Unsupported platform

The relevant error-causing widget was:
  _InheritedI18n
  _InheritedI18n:file:///C:/Users/MLZ/AppData/Local/Pub/Cache/hosted/pub.dev/i18n_extension-8.0.0/lib/i18n_widget.dart:251:12

The line causing the error in i18n_widget:
return _InheritedI18n(
      data: this,
      child: widget.child,
    );

  I am on flutter 3.7.7 and i18n_extension is on 8.0.0. The app is running without a problem on Android.

**Comment by marcglasberg** [comment]
**GPT-4 answer to your question is below. Could you please try it out and tell me if your problem is fixed?**
---

The error message you are seeing, `Unsupported operation: Unsupported platform`, typically occurs when you're trying to use a package or function that depends on platform-specific behavior which is not supported in the current environment. In this case, it's being thrown when you're running your widget tests.

The error message points out the `i18n_extension` package and the `_InheritedI18n` widget as the source of the problem. The `i18n_extension` package is used for internationalization (i18n) - managing different locales and language translations in your Flutter app.

When you're running your app on an Android device, Flutter has access to the Android system's locale settings, so it knows which language and locale to use. However, when you're running widget tests, Flutter doesn't have access to an underlying platform environment (like Android or iOS). Thus, it doesn't know which locale to use and throws an `Unsupported platform` error.

One way to resolve this issue is to manually set the locale in your tests. Here's an example of how you might set up your tests to specify a locale:

```dart
void main() {
  testWidgets('My Widget Test', (WidgetTester tester) async {
    // Provide a fixed Locale for the duration of this test.
    // You can use any Locale you want, here we use US English.
    final locale = Locale('en', 'US');

    // Wrap the widget you're testing with Localizations and provide the locale.
    await tester.pumpWidget(
      MaterialApp(
        localizationsDelegates: const [
          // Add app-specific localization delegate[s] here
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: [locale],
        locale: locale,
        home: // Your widget goes here
      ),
    );

    // Continue with your test
  });
}
```

In this code, we're wrapping the widget under test in a `MaterialApp` and setting the locale to US English ('en', 'US'). This ensures that the widget has a locale during testing, which should avoid the `Unsupported platform` error. The delegates are also added to ensure localization data is available for Material, Widget and Cupertino components. 

Make sure to replace `// Your widget goes here` with the widget that you're actually testing.

If you have specific localization delegates for your app, don't forget to include them in the `localizationsDelegates` array. If you don't have any, then the three global delegates (Material, Widgets, Cupertino) should be sufficient for most cases.

Please note that this is a workaround for the testing environment. In a real app scenario, the system locale is typically used, and you should ensure that your app supports all the locales you intend to support.

**Comment by MLZ91** [comment]
I tried adding the locale, but the error is the same. 

Is noone else using testWdigets or is the error only occuring for me?

**Comment by marcglasberg** [comment]
I am sorry, but I have really no idea what `Unsupported platform` error even is in this context. The line you pointed out simply instantiates an inherited widget, which is a common widget, just regular Dart code that should not depend on specific platforms. I doubt no one else is using `testWidgets`. I don't think I can help you, and I believe you have to do some in-depth investigation. When you do find the problem, could you please let me know what the problem was?

**Comment by marcglasberg** [comment]
Closing this since I got no further information and nobody else reported this. Let me know if you need me to reopen this. Thanks.
