### ISSUE TITLE
Use intl 0.18.0

### ISSUE THREAD

**Issue by robindijkhof** [marcglasberg/i18n_extension#129]
I'm currently on the beta channel which gives me the following message:

Because no versions of i18n_extension match >8.0.0 <9.0.0 and i18n_extension 8.0.0 depends on intl ^0.17.0, i18n_extension ^8.0.0 requires intl ^0.17.0.
And because every version of flutter_localizations from sdk depends on intl 0.18.0, i18n_extension ^8.0.0 is incompatible with flutter_localizations from sdk.
So, because app depends on both flutter_localizations from sdk and i18n_extension ^8.0.0, version solving failed.

**Comment by MLZ91** [comment]
Here is a workaround till this gets done:

`dependency_overrides:
  intl: ^0.17.0`

**Comment by Cierra-Runis** [comment]
flutter new version 3.10 need intl: 0.18.0

**Comment by Cierra-Runis** [comment]
> Here is a workaround till this gets done:
> 
> ```
> dependency_overrides:
>     intl: ^0.17.0
> ```

flutter new version 3.10 need intl: 0.18.0

**Comment by MLZ91** [comment]
> > Here is a workaround till this gets done:
> > ```
> > dependency_overrides:
> >     intl: ^0.17.0
> > ```
> 
> flutter new version 3.10 need intl: 0.18.0

Right, but this overrides it in your project

**Comment by Cierra-Runis** [comment]
> > > Here is a workaround till this gets done:
> > > ```
> > > dependency_overrides:
> > >     intl: ^0.17.0
> > > ```
> > 
> > flutter new version 3.10 need intl: 0.18.0
> 
> Right, but this overrides it in your project. You just have to add this in your pubspec.yaml.

it works now 🙆‍♂️, thanks a lot ❤

**Comment by faizanhub** [comment]
This also worked for me in the flutter 3.10 update with intl:0.18.0 ❤

**Comment by MLZ91** [comment]
> This also worked for me in the flutter 3.10 update with intl:0.18.0 ❤

You dont need to use it anymore, i18n_extension was already updated (v9.0.0)

**Comment by faizanhub** [comment]
But it was giving an error on my project when I updated it to 3.10.

"Because i18n_extension 8.0.0 depends on intl ^0.17.0 and no versions of i18n_extension match >8.0.0 <9.0.0, i18n_extension ^8.0.0 requires intl ^0.17.0.
And because flutter_quill >=7.0.1 depends on i18n_extension ^8.0.0, flutter_quill >=7.0.1 requires intl ^0.17.0.
So, because baby_care depends on both intl ^0.18.0 and flutter_quill ^7.0.9, version solving failed."

**Comment by MLZ91** [comment]
> But it was giving an error on my project when I updated it to 3.10.
> 
> "Because i18n_extension 8.0.0 depends on intl ^0.17.0 and no versions of i18n_extension match >8.0.0 <9.0.0, i18n_extension ^8.0.0 requires intl ^0.17.0. And because flutter_quill >=7.0.1 depends on i18n_extension ^8.0.0, flutter_quill >=7.0.1 requires intl ^0.17.0. So, because baby_care depends on both intl ^0.18.0 and flutter_quill ^7.0.9, version solving failed."
use i18n_extension: ^9.0.0 in your pubspec.yaml

**Comment by faizanhub** [comment]
Still giving error 

```
Because flutter_quill 7.1.18 depends on i18n_extension ^8.0.0 and no versions of flutter_quill match >7.1.18 <8.0.0, flutter_quill ^7.1.18 requires i18n_extension ^8.0.0.
So, because baby_care depends on both i18n_extension ^9.0.0 and flutter_quill ^7.1.18, version solving `failed.
```

`name: baby_care
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.3+4

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  provider: ^6.0.3
  flutter_bloc: ^8.1.1
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15

  #hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  hive_generator: ^2.0.0

  responsive_sizer: ^3.1.1
  flutter_svg: ^1.1.5
  google_fonts: ^4.0.4
  dropdown_button2: ^1.8.5
  permission_handler: ^10.1.0

  #firebase
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
  firebase_messaging: ^14.3.0

  ndialog: ^4.2.0
  google_sign_in: ^5.4.2
  crypto: ^3.0.2
  sign_in_with_apple: ^4.1.0
  flutter_facebook_auth: ^4.4.1+1
  audio_video_progress_bar: ^0.11.0


  email_auth: ^1.0.0
  syncfusion_flutter_datepicker: ^20.3.52
  fl_chart: ^0.55.2
  google_nav_bar: ^5.0.6
  image_cropper: ^3.0.1
  file_picker: ^5.2.2

  flutter_switch: ^0.3.2
  syncfusion_flutter_sliders: ^20.3.58

  url_launcher: ^6.1.7
  flutter_linkify: ^5.0.2
  day_picker: ^2.1.1

  syncfusion_flutter_charts: ^20.3.58
  intl: ^0.18.0
  timeago: ^3.3.0
  flutter_share: ^2.0.0

  flutter_local_notifications: ^9.9.1
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  datetime_picker_formfield: ^2.0.1

  stop_watch_timer: ^2.0.0
  just_audio: ^0.9.30
  #just_audio_background: ^0.0.1-beta.8
  http: ^0.13.5
  rate_my_app: ^1.1.3

  flutter_background_service: ^2.4.6

  google_mobile_ads: ^2.3.0
  i18n_extension: ^9.0.0

#  flutter_quill: ^7.0.9
  flutter_quill: ^7.1.18
  flutter_localizations:
    sdk: flutter



#dependency_overrides:
#  intl: ^0.18.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  hive_generator: ^2.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:


  assets:
    - assets/
    - assets/addVaccine/
    - assets/appointment/
    - assets/community/
    - assets/details/
    - assets/drawer/
    - assets/fonts/
    - assets/guidelines/
    - assets/medication/
    - assets/svg/
    - assets/svg/add_baby/
    - assets/svg/baby_profile/
    - assets/svg/caretaker_profile/
    - assets/svg/home_screen/
    - assets/svg/memories/
    - assets/svg/secondparent_profile/
    - assets/svg/trace_behaviour_crying/
    - assets/svg/trace_behaviour_sleep/
    - assets/svg/trace_feed_breast/
    - assets/svg/trace_weight/
    - assets/trace_nappies/
    - assets/tracefood/
    - assets/flags/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Comment by MLZ91** [comment]
Oh yeah, in your case you still have to use the workaround because of flutter_quill.

**Comment by marcglasberg** [comment]
Closing this, as the newest version updated to use intl 0.18.
