### ISSUE TITLE
There are no translations in 'en_us' for "Aug"

### ISSUE THREAD

**Issue by edwin-alvarez** [marcglasberg/i18n_extension#142]
var f = DateFormat("MMM");
        String formattedDate = f.format(d);
        return formattedDate.i18n; <-- this not able to find the translation

looks like above line is not translating because my Locale("en") is not found it is trying to find en_us

I don't have access to context yet when trying to translate, because that's being call at main() thus instead of calling 
        I18n.of(context).locale = const Locale("en");

I was trying to call 
        I18n.define(const Locale("en"));
but that marked for testing 
///This should be used in tests ONLY. The real app, you should
  /// instead do: `I18n.of(context).locale = Locale("en", "US");

this works, but I'm worry I'm doing something not correct, or that method gets deprecate/remove

**Comment by marcglasberg** [comment]
Hey @edwin-alvarez sorry for the delayed response.

The reason `I18n.define()` should be used in tests only is generally because if you just change a value directly like this, it will not tell the widgets to rebuild. If this is done in main instead of later in a widget, I think this is not a problem. You can do it, and that method will not get deprecated, don't worry.

The only thing that surprises me is this line: `formattedDate.i18n`. I say this because `DateFormat("MMM").format()` should already give you the date formatted to your locale. In other words, Dart should already localize the date for you
**according to our locale**, so that you wouldn't need to use i18n_extension for that date formatting:

```dart
/// Return a string representing [date] formatted according to our locale and internal format.
String format(DateTime date) { ... }
```

Maybe you shouldn't be doing any of this in main.
