### ISSUE TITLE
Printing missing keys via tests

### ISSUE THREAD

**Issue by BassamxMednini** [marcglasberg/i18n_extension#16]
I'm a little bit confused. I'm trying to add some tests, just to get in touch with it but for some reason it doesn't work as I expected. Actually, I'm trying to understand this example:

    Translations.missingKeys.clear();
    Translations.missingTranslations.clear();

    // This should call recordKey().
    "Hello World".i18n;

    expect(Translations.missingKeys.length, 1);
    expect(Translations.missingKeys.single.locale, "");
    expect(Translations.missingKeys.single.text, "Marked habit");
    expect(Translations.missingTranslations, isEmpty);

When I'm running the test file, I get the output `➜ Translation key in '' is missing: "Hello World".`. Why the output doesn't show the locale?

**Comment by marcglasberg** [comment]
This is the recordKey function:

```
/// This simply records the given key as a missing translation with unknown locale.
String recordKey(String key) {
  if (Translations.recordMissingKeys)
    Translations.missingKeys.add(TranslatedString(locale: "", text: key));

  Translations.missingKeyCallback(key, "");

  return key;
}
```

As you can see above, the locale is defined as `locale: ""`

The reason is, it doesn't know the locale `"Hello World"` is supposed to be. How could it know? I just knows there is some string for which a key was not defined.

Maybe a better error message would be:

`➜ Translation key with unknown locale is missing: "Hello World".`

Or, simply:

`➜ Translation key is missing: "Hello World".`
