### ISSUE TITLE
No fallback?

### ISSUE THREAD

**Issue by JCKodel** [marcglasberg/i18n_extension#2]
Considering:

```dart
static var t = Translations("pt") +
    {
      "pt": "ENTRAR COM GOOGLE",
      "en": "ENTER WITH GOOGLE",
      "es": "INICIA COM GOOGLE",
    };
```

Results in:
```
➜ There are no translations in 'pt_br' for "ENTRAR COM GOOGLE".
```

I was expecting something like pt_pt, pt_ao, pt_br too fallback to pt (I'm lazy and don't want to translate every variant of portuguese, english and spanish)

BTW, my phone is en_US (don't know why it is trying to find pt_br)

**Comment by marcglasberg** [comment]
It should fallback, yes. It should try, in order:

1) The exact locale (for example, if the device is "pt_br" and it finds "pt_br").  
2) Then the general language  (for example, if the device is "pt_br" and it finds "pt").  
3) Then any locale with that language (for example, if the device is "pt_br" and it finds "pt_ao").  

But, at the moment, the locale in the constructor should not be general. Try `Translations("pt_br")` instead of `Translations("pt")`.

In other words, try this:

    static var t = Translations("pt_br") +
      {
      "pt_br": "ENTRAR COM GOOGLE",
      "en": "ENTER WITH GOOGLE",
      "es": "INICIA COM GOOGLE",
      };

If it doesn't work, please let me know.

But even if it works, you are right that it should accept `Translations("pt")`. In a future version I will change that. I just need Dart 2.6 to go to the stable channel so that I can work in this package again.

Also, have a look at https://github.com/marcglasberg/i18n_extension/blob/master/test/i18n_extension_test.dart and see that it tests the fallbacks. If you can, try to modify some of the tests there to create a failing test to help me fix the problem.

**Comment by JCKodel** [comment]
Could not work either way... The strings always remains in portuguese, even if OS is english.

**Comment by marcglasberg** [comment]
Ok, no problem. Can you please provide me with some minimum runnable code (with main method and all) demonstrating the problem? I need to reproduce it to be able to fix it.

**Comment by JCKodel** [comment]
Working as this:

On main.dart:
```dart
return MaterialApp(
      debugShowCheckedModeBanner: false,
      navigatorKey: Catcher.navigatorKey,
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [Locale("pt"), Locale("en"), Locale("es")],
      localeResolutionCallback: (locale, locales) {
        print("FALLBACK TO ${locale.toLanguageTag()}");

        if (locale.languageCode == "pt") {
          return const Locale("pt", "BR");
        } else if (locale.languageCode == "en") {
          return const Locale("en");
        } else if (locale.languageCode == "es") {
          return const Locale("es");
        }

        return const Locale("en");
      },
```
(needed to fallback to pt-BR when language is pt-*, otherwise, it won't work)

Then, with this translations:

```dart
  static var t = Translations("pt_br") +
      {
        "pt_br": "ENTRAR COM GOOGLE",
        "en": "ENTER WITH GOOGLE",
        "es": "INICIA COM GOOGLE",
      };
```

Now it works as intended (with my phone set to English United State, it calls the fallback code, so I set it to "en" and it works).

**Comment by marcglasberg** [comment]
You must wrap your widgets with `I18n(child: ...)` and you don't seem to be doing that:

```dart
@override
Widget build(BuildContext context) {
 return MaterialApp(
   home: I18n(child: ...)
 );
}
```
