### ISSUE TITLE
Default language not working

### ISSUE THREAD

**Issue by robindijkhof** [marcglasberg/i18n_extension#24]
It seems to be the default language (fallback) is not working. If some unknown language is set, for example, de_DE, the dutch(nl) translation is shown. Any English locale will display the English translation.

Main:

    class MyApp extends StatelessWidget {
        
      @override
      Widget build(BuildContext context) {
        return MaterialApp(

          title: 'Timesheet',
          home: I18n(child: LoginScreen()),
          debugShowCheckedModeBanner: false,
          localizationsDelegates: [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: const [
            Locale('nl', 'NL'), // nl
            Locale('en', 'US'), // English
            Locale('en', 'UK'), // English
          ]
        );
      }
    }

Translation:

    extension Localization on String {
      String get i18n => localize(this, t);
    
      String plural(int value) => localizePlural(value, this, t);
      static var t = Translations('en') +
          {
            'en': 'Sign in success',
            'nl': 'Inloggen gelukt',
          } +
          {
            'en': 'Sign in fail',
            'nl': 'Inloggen mislukt',
          } +
          ...
    }

adding the following seems to fix the issue.

     localeResolutionCallback: (locale, locales) {
        print("FALLBACK TO ${locale.toLanguageTag()}");

        return locale;
      },

**Comment by marcglasberg** [comment]
By reading https://api.flutter.dev/flutter/widgets/WidgetsApp/localeResolutionCallback.html and https://api.flutter.dev/flutter/widgets/WidgetsApp/supportedLocales.html I'd say it's defaulting to `NL` because that's the first locale in the `supportedLocales` list you provided.

When you provide your `localeResolutionCallback` you are overriding the `supportedLocales` list, and then it really uses the `de_DE` locale, which doesn't exist, so it will then default to English.

You probably can obtain the same result by removing `localeResolutionCallback` and then putting `Locale('en', 'US')` as the first item in the `supportedLocales` list.

My `i18n_extension` can't really change the way the proper locale is decided by the `MaterialApp` widget.

**Comment by robindijkhof** [comment]
Read that somewhere before, but didn't seem to make a difference. I'll try agian
