### ISSUE TITLE
The current iOS system locale always seems to be en_US

### ISSUE THREAD

**Issue by maguro** [marcglasberg/i18n_extension#29]
I changed the locale on my iPhone, iOS 13.3.1 to Spanish and the region to Mexico.  However, The mechanisms this extension seems to use seem to be stuck at en_US.

**Comment by maguro** [comment]
It seems that one needs to add an `es` localization in Xcode, per https://github.com/flutter/flutter/issues/14128.   However, the way `I18n` picks up its locale, it obtains the correct local after its child widgets have been built and it doesn't bother rebuilding them.

**Comment by lucas-sesti** [comment]
Hey, i facing with same issue, but i can resolve my problem changing the development language, in project.pbxproj have the:
DevelopmentRegios = en; // Change this to your language (or the language you want) (example: French = fr, Portuguese = pt...)

and have the knownRegions too, you need change, my knowRegions is default = 
knownRegions = (
    en,
    Base,
),
and i added in first my language, and its works to mee, if not working, we'll try find your problem

**Comment by marcglasberg** [comment]
Maybe it has something to do with this issue: https://github.com/flutter/flutter/issues/14128

What do you think?

**Comment by lucas-sesti** [comment]
Yes... but i can't resolve just seeing this issue... i found in a post of stackoverflow (i don't have the link anymore, but i'll try again)

**Comment by marcglasberg** [comment]
@lucas-sesti Ok!

@maguro Does that solve your problem?

**Comment by suesitran** [comment]
I tried solution from https://github.com/flutter/flutter/issues/14128, it works in debug but failed in release build. Any other clue?

**Comment by lucas-sesti** [comment]
@suesitran Did you try what i said? Because i tested in debug and release build, and both works

**Comment by suesitran** [comment]
Yes I tried it, does not work. My development region is English (not sure if i have to change to en), and known region is (en, Base)

**Comment by lucas-sesti** [comment]
Probably you don't need change to en.. but, if you want change to other languages, you need put in first options off knownRegions and in development region

**Comment by Kelvne** [comment]
I can vouch for the solution.

The following code wasn't working properly:

```dart
localeListResolutionCallback: (locales, supported) {
  Locale locale = Locale('en', 'US');

  for (var loc in locales) {
    if (supported.contains(loc)) {
      locale = loc;
      break;
    }
  }

  return locale;
}
```

Even though the Device's Locale was set to a different language the `locales` parameter was returning: `[en_US, pt_BR, en]`. Not honoring the priority set on the device.

**The solution**:
- Add the supported languages on the XCode project (picture 1).
- Add `Localized resources can be mixed` to `YES` on the `Info.plist` (picture 2).

_References:_
_(Picture 1)_
<img width="1153" alt="Screen Shot 2020-04-22 at 18 23 05" src="https://user-images.githubusercontent.com/1118492/80035589-a97aa680-84c6-11ea-9b41-2f4188855bd0.png">

_(Picture 2)_
<img width="535" alt="Screen Shot 2020-04-22 at 18 24 50" src="https://user-images.githubusercontent.com/1118492/80035664-c8793880-84c6-11ea-84e5-728a6b17e8ba.png">

After those settings set, the locales param is rightfully being returned as `[pt_US, pt_BR, en]`
_(`pt_US` in this case is expected to be first because the phone region is set to the USA)_

**Comment by ivan-pavliuk** [comment]
Any updates on it?

**Comment by marcglasberg** [comment]
@maguro
@lucas-sesti
@suesitran
@kelvne
@ivan-pavliuk

Version **14.0.0-dev.1** should fix this once and for all. 

If you run the example app in `i18n_extension\example\lib\1_translation_example` you can test this. Tap the globe icon at the top-right of the screen. A new screen will open that prints many values, including the value of `I18n.systemLocale`. This should change automatically when you change the system locale in both Android and iOS.

Also, please check the CHANGELOG:

---

## 14.0.0-dev.1

Version 14 brings important improvements, like new interpolation methods, useful
extensions, and improved standardization, with the cost of a few breaking changes that
are easy to fix. Please, follow the instructions below to upgrade your code.

* **Breaking Change**: Now, you must have a single (no more than one) `I18n` widget in
  your entire widget tree, and it must always be put ABOVE the `MaterialApp`
  (or `CupertinoApp`) widget, in the tree. There, it will be able to provide translations
  to all your routes and dialogs.


* **Breaking Change**: You must now add the line `locale: I18n.locale` to your
  `MaterialApp` (or `CupertinoApp`) widget, like this:

  ```
  MaterialApp(
     locale: I18n.locale,
     ...      
  ``` 


* **Breaking Change**: Because of the way Flutter works, you have to make sure your `I18n`
  widget is NOT declared in the same widget as the `MaterialApp`, but in a **parent**
  widget. For example, this is WRONG:

  ```dart
  Widget build(BuildContext context) {
    return I18n( // Wrong!
      child: MaterialApp(
        home: MyScreen(),
  ```        

  Instead, this is how your `main.dart` file could look like:

  ```dart    
  import 'package:i18n_extension/i18n_extension.dart';
  import 'package:flutter_localizations/flutter_localizations.dart';
         
  void main() {
    WidgetsFlutterBinding.ensureInitialized();
    runApp(MyApp());
  }
  
  class MyApp extends StatelessWidget {
    Widget build(BuildContext context) {
      return I18n( // I18n in a parent widget!
        child: AppCore(),
      );
    }
  }
  
  class AppCore extends StatelessWidget {
    Widget build(BuildContext context) {
      return MaterialApp( // MaterialApp is here!
        locale: I18n.locale, // Locale declaration is here!
        localizationsDelegates: [ ... ],
        supportedLocales: [ ... ],
        home: ...
      ),
  ```  

  Another good alternative is declaring the `I18n` widget directly inside the `runApp`
  call, in your `main` function:

  ```dart    
  void main() {
    WidgetsFlutterBinding.ensureInitialized();
    runApp(I18n(child: AppCore())); // I18n in a parent widget!
  }
  
  class AppCore extends StatelessWidget {
    Widget build(BuildContext context) {
      return MaterialApp( // MaterialApp is here!
        locale: I18n.locale, // Locale declaration is here!
        localizationsDelegates: ...
      ),
  ```  


* **Breaking Change**: The `MaterialApp` (or `CupertinoApp`) widget contains, internally,
  a `Localizations` widget, which is used by Flutter to provide translations to all native
  Flutter widgets.
  The `I18n` widget will now automatically keep in sync with this `Localizations` widget,
  so that when you change the locale in `I18n` (with `context.locale = 'en-US'.asLocale`,
  for example), it will also change automatically in the `Localizations` widget. This
  means that `Localizations.of(context).locale` will always return the same result as
  `I18n.of(context).locale`, as `context.locale`, and as `I18n.locale`.

  If you previously had your own logic to change the native `Localizations` locale by
  changing the `locale` parameter of the `MaterialApp` widget, you can now remove it,
  as this is not necessary anymore.


* **Breaking Change**: Language codes must now respect the BCP47 standard, when you
  define your translations.  
  For example, you should now use `en-US` instead of the old `en_us` format.
  Other valid code examples are: `en`, `es-419`, `hi-Deva-IN` and `zh-Hans-CN`.

  This is an example of a WRONG translation definition:

  ```dart     
  // Will throw: Locale "en_us" should be "en-US" 
  Translations.byText('en_us') + // Wrong!
     {
        'en_us': 'Hello, how are you?',  // Wrong!
        'pt_br': 'Olá, como vai você?',  // Wrong!
        'es': '¿Hola! Cómo estás?',
        'fr': 'Salut, comment ca va?',
        'de': 'Hallo, wie geht es dir?',
     };
  ```                                                                          

  To help you upgrade, a `TranslationsException` error will be thrown when you use the
  old code format. The error message will be something like:
  `Locale "en_us" should be "en-US"`

  This is an example of a VALID and correct translation definition:

  ```dart
  Translations.byText('en-US') +
     {
        'en-US': 'Hello, how are you?',
        'pt-BR': 'Olá, como vai você?',
        'es': '¿Hola! Cómo estás?',
        'fr': 'Salut, comment ca va?',
        'de': 'Hallo, wie geht es dir?',
     };
  ```

  Note: If your translations are defined manually in the code, you can quickly fix this
  by doing a few _Search and Replace_ commands in your IDE to fix the language codes, one
  for each of your supported languages, for example, replacing `'en_us'` with `'en-US'`
  etc.


* New extension `Locale.format` can be used to return the string representation of the
  Locale as a valid BCP47 language tag (compatible with the Unicode Locale Identifier
  (ULI) syntax). If the locale is not valid, `format` may return an invalid tag, or may
  return string "und" (undefined).  
  The language code, script code, and country code will be separated by a hyphen,
  and any lowercase/uppercase issues will be fixed. For example:

  ```dart
  var locale = Locale('en', 'us');
  print(locale.format()); // en-US, which is a valid BCP47 language tag
  print(locale.toString()); // en_US
  print(locale.toLanguageTag()); // en-us
  ```

  Using `format` is recommended over `toString` and `toLanguageTag` (both natively
  provided by the `Locale` class). In more detail:

    - `Locale.format()` returns the string representation of the Locale as a valid BCP47
      language tag, fixing any lowercase/uppercase issues and separating components with
      a hyphen. Allows specifying a different separator. For example,
      `Locale('en', 'us').format()` returns `en-US`, and
      `Locale('en', 'US').format(separator: '|')` returns `en|US`.

    - `Locale.toString()` returns the language, script and country codes separated by an
      underscore. For example, `Locale('en', 'us').toString()` returns `en_us`
      and `Locale('en', 'US').toString()` returns `en_US`.

    - `Locale.toLanguageTag()` returns the language code and the country code separated by
      a hyphen, but does not fix case. For example, `Locale('en', 'us').toLanguageTag()`
      returns `en-us`, and `Locale('en', 'US').toLanguageTag()` returns `en-US`.


* New extension `String.asLocale` can be used to convert a `String` containing a BCP47
  language tag to a `Locale` object. For example: `Locale locale = 'pt-BR'.asLocale;`.
  If the string is not a valid BCP47 language, `asLocale` will try to fix it.
  For example, the following lines are all **equivalent** and result in the same locale:

  ```dart
  var locale = Locale('en', 'US'); 
  var locale = 'en-US'.asLocale; 
  var locale = 'en_US'.asLocale; 
  var locale = 'en-us'.asLocale; 
  var locale = 'EN-US'.asLocale; 
  var locale = 'en US'.asLocale; 
  var locale = 'en|US'.asLocale; 
  var locale = 'en.uS'.asLocale; 
  var locale = 'eN,US'.asLocale; 
  var locale = 'en;US'.asLocale; 
  var locale = 'en, US'.asLocale; 
  ```

  However, it will only fix the most common errors, by fixing lowercase/uppercase issues,
  removing spaces, and converting all these separators: `-` `_` ` ` `|` `.` `,` `;` to
  hyphens. If it can’t fix it, it will return an invalid `Locale`, or maybe
  `Locale('und')`, meaning the locale is undefined.

  Note that `String.asLocale` can be used whenever you previously used Locale
  constructors. For example, instead of:

  ```dart
  supportedLocales: [
    Locale('en', 'US'),
    Locale('es', 'ES'),
  ],
  ```

  You can now write:

  ```dart
  supportedLocales: [
    'en-US'.asLocale,
    'es-ES'.asLocale,    
  ],
  ```


* New extension `String.asLanguageTag` can be used to try and normalize String language
  tags to the BCP47 standard (which is compatible with the Unicode Locale Identifier
  (ULI) syntax). It fixes casing (uppercase and lowercase), removes spaces, and turns
  underscores into hyphens. As such, it can be used to convert the old format language
  tags to the new ones. For example: `'en_us'.asLanguageTag` returns `'en-US'`.


* **Interpolations.** You can now do string interpolations by replacing placeholders with
  values, with the `args` function:

  ```dart
  // Hello John and Mary
  'Hello {} and {}'.i18n.args('John', 'Mary');
  
  // Also works with iterables
  'Hello {} and {}'.i18n.args(['John', 'Mary']);
  
  // Named placeholders
  'Hello {name} and {other}'.i18n.args({'name': 'John', 'other': 'Mary'});
  
  // Numbered placeholders
  'Hello {1} and {2}'.i18n.args({1: 'John', 2: 'Mary'});
  
  // And you can mix placeholder types
  'Hello {name}, let’s meet up with {} and {other} to explore {1} and {2}.'.i18n.args('Charlie', {'name': 'Alice', 'other': 'Bob'}, {1: 'Paris', 2: 'London'});
  ```   

  For all the details, check the README.md file.


* **Breaking Change**: Previously, you could also do string interpolation by using
  **sprintf** specifiers, like `%s`, `%1$s`, `%d` etc., and providing a list of values to
  fill them. This is still supported:

  ```                   
  // Hello John and Mary
  'Hello %s and %s'.i18n.fill(['John', 'Mary']);
  
  // Hello John and Mary
  'Hello %1$s and %2$s'.i18n.fill(['John', 'Mary']);  
  
  // Hello Mary and John  
  'Hello %2$s and %1$s'.i18n.fill(['John', 'Mary']);  
  ```

  However, you can now also provide the values directly, without having to wrap them
  in a list:

  ```
  'Hello %s and %s'.i18n.fill('John', 'Mary');
  'Hello %1$s and %2$s'.i18n.fill('John', 'Mary');
  'Hello %2$s and %1$s'.i18n.fill('John', 'Mary');
  ```

  The breaking change part of it is that, previously, if you wanted to use the `fill`
  extension you needed to declare it yourself in your translations files. Now, that's not
  necessary anymore, as this extension is provided out of the box. For this reason, if you
  declared the `fill` extension yourself, you now need to remove it. Otherwise, the
  compiler will complain that the extension is declared twice. If you still want to keep
  your old declaration, change its name.


* **Auto saving the locale.** Some apps may allow the user to change the language/locale
  of the app, from inside the app. You'd usually create some widget that presents the list
  of available locales, and then set it with `context.locale = 'es-ES'.asLocale;` or
  similar.

  If you want that user choice to be saved between app restarts,
  simply set the `autoSaveLocale` parameter to `true`:

  ```dart
  I18n(
    autoSaveLocale: true,
    child: AppCore(),
    ...
  ```

  This will automatically save changes to the locale in the device's storage
  (shared preferences), and restore it when the app restarts.
  Note the locale is read asynchronously, which may result in a one frame flicker
  of the default system locale, before the saved locale is restored. If you want to avoid
  this flicker, you can explicitly preload the locale yourself by doing
  `initialLocale: await I18n.loadLocale()` when the app starts.

  ```dart    
  void main() async {
    WidgetsFlutterBinding.ensureInitialized();
   
    runApp(
      I18n(
        initialLocale: await I18n.loadLocale(),
        autoSaveLocale: true, 
        child: AppCore(),    
        ...
  ```

  > Note: While usually not needed, you can also manually load, save and delete the
  > locale from the shared preferences, at any later time,
  > by using the provided static functions:
  > `var locale = await I18n.loadLocale()`, `I18n.saveLocale(locale)`
  > and `I18n.deleteLocale()`.


* You can get the current locale by using the `context`:

  ```dart
  Locale locale = context.locale;
  Locale locale = I18n.of(context).locale;
  ```

  However, you can also get the locale **statically**,
  allowing you to use it in non-widget code:

  ```dart
  // Get a `Locale` object, like Locale('en', 'US') 
  Locale locale = I18n.locale;
  
  // Or get a BCP47 language tag string, like 'en-US'
  String languageTag = I18n.languageTag;
  String languageTag = I18n.locale.format();
  
  // Or get a locale string with a specific separator, like 'en|US'
  String languageTag = I18n.locale.format(separator: '|');
  
  // Or get only the lowercase language code part of the locale, like 'en'.
  String language = I18n.language;
  ```

  Note, using `I18n.localeStr` is deprecated. It returns a lowercase string with
  underscores, like `en_us`.


* To change the current locale, do this:

  ```dart
  context.locale = Locale('pt', 'BR');
  
  // Or
  context.locale = 'pt-BR'.asLocale;
  
  // Or
  I18n.of(context).locale = 'pt-BR'.asLocale;
  ```

  To reset the current locale back to the default **system locale**, do this:

  ```dart
  context.locale = null;
  
  // Or
  context.resetLocale();
  
  // Or
  I18n.of(context).locale = null;
  
  // Or
  I18n.of(context).resetLocale();
  ```

  Note, any of the above will change the current locale for your widgets using
  the `i18n_extension`, and also for native Flutter widgets.


* **Breaking Change**: The fallback rules changed a little bit.
  What happens when you don’t provide the translations for the current locale?
  For example, suppose your current locale is Spanish, but you have only provided
  translations for English and French.
  Fallback behavior is now more intuitive and aligned with common sense.
  In most cases, it will do exactly what you’d expect.
  However, if you want all the details, check the README.md file.
