### ISSUE TITLE
Translation key in '' is missing: "Something"

### ISSUE THREAD

**Issue by luizwalber** [marcglasberg/i18n_extension#32]
Hello, I've really loved the plugin

but when I tried to use it in a personal project it always returns Translation key in '' is missing: "Something". 

it's not recognizing the Locale?

My project is this: https://github.com/luizwalber/TaskManager

It's a mess, I'm learning and building it

the translations are in the main.i18n.dart file and I use the .i18n in the files inside ui->screens

Thanks a lot for the plugin, the way to implement internationalization in flutter is horrible.

**Comment by marcglasberg** [comment]
I can't really go through a complex project like this to find the problem. I have 3 suggestions for you:

1) Carefully go through the i18n_extension documentation, and try to see if you have done something wrong.

2) If you can't find the problem, create a **single file**, as simple as possible, with a `main` method and all, runnable, to try the package out. This seems to help most people find out what the problem is. And then, if you can't make it work with a single file, that's something I can have a look at.

3) And, I couldn't help notice you are using Redux. Have you tried https://medium.com/flutter-community/https-medium-com-marcglasberg-async-redux-33ac5e27d5f6  /  https://pub.dev/packages/async_redux ?

**Comment by luizwalber** [comment]
Sorry for the big project,

I've solved, I was importing "import 'package:i18n_extension/default.i18n.dart';" in the files that needed to use translations, when I needed to import my extension file, when I changed the import the IDE reported Unused for both, I removed the default and everything worked fine 

Thanks a lot, 

Excellent plugin

**Comment by redbasecap** [comment]
Thx a lot! @luizwalber
