### ISSUE TITLE
Change static to get for a hot reload

### ISSUE THREAD

**Issue by onemanstartup** [marcglasberg/i18n_extension#36]
Right now every documentation is tells to write static fields. But this doesn't work with hot reload. I suggest to change this to getter 
```dart
extension Localization on String {
  get _t =>
      Translations("en") +
      {
        "en": "Forgot Password?",
        "ru": "Забыли Пароль?",
      };

  String get i18n => localize(this, _t);
}
```

**Comment by edwin-alvarez** [comment]
i have been wondering how to enable hot reload. **this is great** :) thanks

**Comment by marcglasberg** [comment]
@onemanstartup  @edwin-alvarez This is not really good. Each time you localize a string it will recreate the translations map. Probably not noticeable in most cases, but terribly inefficient. I'll have a look as soon as I can and propose something different.

**Comment by edwin-alvarez** [comment]
@marcglasberg , thanks for the feedback, i was very happy using his workaround, but, I'll roll the change back.

**Comment by marcglasberg** [comment]
@edwin-alvarez You can use the workaround during development, to help with hot-reload, and then change it back for release. Meanwhile I will try and find a better way.

**Comment by edwin-alvarez** [comment]
You nail it, that's exactly what we decided to do.

**Comment by marcglasberg** [comment]
The default `Translations` constructor builds an empty translations object, that can be filled with translations with the `[+]` operator. For example:

```
static final t = Translations("en_us") +
       const {
         "en_us": "i18n Demo",
         "pt_br": "Demonstração i18n",
       };
```

However, now there is also the `Translations.from` constructor, which responds better to hot reload. It allows you to define the translations as a `const` object, all at once. This not only is a little bit more efficient, but it's also better for hot reload, since a `const` variable does respond to hot reloads, while `final` variables will not (see: https://flutter.dev/docs/development/tools/hot-reload#recent-code-change-is-included-but-app-state-is-excluded). 

The syntax, however, is different:

```
static const t = Translations.from(
    "en_us",
    {
      "i18n Demo": {
        "en_us": "i18n Demo",
        "pt_br": "Demonstração i18n",
      }
    },
 );
```

Another solution, as discussed above, is using the getter workaround during development, to help with hot-reload, and then change it back for release.
