### ISSUE TITLE
How use i18n_extension in Isolate ?

### ISSUE THREAD

**Issue by EArminjon** [marcglasberg/i18n_extension#37]
Hi,

I've background task running in isolate, some of them throw message like this "content_of_message".i18n. Obviously i18n is not loaded in isolate, i didn't have context, so message aren't translated :).

I used to achieve that  I18n.define(Locale(locale)); It works, but I got some warning because it must be used only in test environnement.

What is the best way to use i18n_extension in isolate ?

**Comment by marcglasberg** [comment]
Sorry, but I don't have experience with isolates. Do you like me to remove the @visibleForTesting annotation so that you don't get those warnings anymore? Would that solve your problem?

**Comment by EArminjon** [comment]
Hum, I just start with isolate and i didn't know what is the best way... I don't want to force you to edit the source code if i go wrong :/

I18n.define just change locale without call method for rebuild right ?

**Comment by marcglasberg** [comment]
To be honest with you: I have published 11 packages, and also have my main project to take care of, so my brain cannot keep all of the details at the same time. I am not sure now, but by looking at `I18n.define` it doesn't seem to rebuild. Only when `_I18nState.locale` is set it calls `setState`, which calls the `build` method, which calls `_rebuildAllChildren` to mark the whole tree below it as dirty.

You can, of course, add a `print("REBUILD")` into `_I18nState.build()` to see when it gets rebuild.

If you are having problems with isolates I am sure this is of interest to other people. So it would be really nice if you solve this problem! But try to make sure you come up with the right solution because I am not able to make sure to check if it is OK at the moment.

If you do come up with a solution I should probably add a section in the docs explaining how to deal with isolates. Would you mind suggesting the text for this explanation?
