### ISSUE TITLE
Provide example for JSON import loadTranslations

### ISSUE THREAD

**Issue by HelloBytes** [marcglasberg/i18n_extension#63]
By now you can use the JSON import function that is great, thank you. But it's not clear to me where and how I can import my json translations. 

I want to use a central json file for all translations through the app. The best way I think is to load the translation file one time into a variable that is used by _extension Localization on String_. Or do I have to load the translation file every time I need the .i18n extension?

**Comment by marcglasberg** [comment]
The JSON import was contributed by Johann Bauer. I don't actually use it, so you have to post this question to him: @bauerj

**Comment by bauerj** [comment]
Hey HelloBytes,

so do you want to have one localisation file per language (but with all translations for the entire app) or one file with all languages included?

The first use-case is currently supported, the second one isn't. I can share an example later if you want.

**Comment by bauerj** [comment]
Okay, so this is what I'm using in https://github.com/bauerj/paperless_app:

**i18n.dart**:
```Dart
import 'package:i18n_extension/io/import.dart';

import 'package:flutter/widgets.dart';
import 'package:i18n_extension/i18n_extension.dart';

class MyI18n {
  static TranslationsByLocale translations = Translations.byLocale("en_GB");

  static Future<void> loadTranslations() async {
    translations +=
        await GettextImporter().fromAssetDirectory("assets/locales");
  }
}

extension Localization on String {
  String get i18n => localize(this, MyI18n.translations);
  String plural(int value) => localizePlural(value, this, MyI18n.translations);
  String fill(List<Object> params) => localizeFill(this, params);
}

```

Then, during app startup I call `MyI18n.loadTranslations();`. Nothing else is required, except for placing `I18n` somewhere in your widget tree. Pretty neat.

I actually struggled to find out how to do this initially as well. However, I'm not entirely sure this is the right way to do it. For example, I don't know whether layouting can start **after** loading the translations. Will the widgets just update when changing `MyI18n.translations`? Otherwise we should find a better way and maybe add it to the documentation.

Maybe @marcglasberg can shed some light here?

**Comment by HelloBytes** [comment]
> Hey HelloBytes,
> 
> so do you want to have one localisation file per language (but with all translations for the entire app) or one file with all languages included?
> 
> The first use-case is currently supported, the second one isn't. I can share an example later if you want.

Thank you for your feedback!

A example would be great!

**Comment by bauerj** [comment]
> Thank you for your feedback!

This was more of a question and not feedback 😄The second way wouldn't be too hard to support either, if you want.

**Comment by bauerj** [comment]
I just investigated this further and indeed, there is a race condition when the translation gets loaded after the widgets were drawn.

Since it seems better to have users wait a few milliseconds than to have English strings be exchanged for their native language when loading the app, this is what I came up with:

```Dart
class _PaperlessAppState extends State<PaperlessApp> {
  Future<void> loadAsync;

  // This widget is the root of the application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: FutureBuilder(
        future: loadAsync,
        builder: (BuildContext context, AsyncSnapshot<void> snapshot) {
          if (snapshot.connectionState == ConnectionState.done)
            return I18n(
              child: HomeRoute(),
            );
          return Center(
              child: SizedBox(
            height: 155.0,
            child: SvgPicture.asset(
              "assets/logo.svg",
              color: Colors.lightGreen,
              fit: BoxFit.contain,
            ),
          ));
        },
      )
    );
  }

  @override
  void initState() {
    super.initState();
    loadAsync = MyI18n.loadTranslations();
  }
}
```

Essentially, this only creates the I18n widget after the translation has been loaded from disk.

**Comment by marcglasberg** [comment]
@bauerj Do you think it's worth it adding this code example to the docs? Also, can I close this issue?

**Comment by bauerj** [comment]
> Do you think it's worth it adding this code example to the docs?

Sure, why not. It helps people get started. Maybe at this point it would make sense to have multiple files to organise the docs? The README might be a bit overwhelming if you don't want to have all the details.

> Also, can I close this issue?

I guess so, although of course @HelloBytes would have to say.

**Comment by bauerj** [comment]
By the way, would you like me to update the example app? Or maybe we should have two example apps: one for the "traditional" way and one for the gettext/json way.

**Comment by HelloBytes** [comment]
Ok thanks for the example. I have to test this, but its look like a good way to load the translation thanks! So you can close the issue.

**Comment by marcglasberg** [comment]
@bauerj Two examples would be much better.

**Comment by marcglasberg** [comment]
@HelloBytes @bauerj 

Version [14.0.0-dev.3] provides a new way to load translations from a file. See the CHANGELOG and the README:

* **Load translations from files**. If you want to load translations from files in your assets directory, create a folder and add some translation files like this:

  ```
  assets
  └── translations
      ├── en-US.json
      ├── es-ES.json
      ├── zh-Hans-CN.json
      └── pt.json 
  ```

  Don't forget to declare your assets directory in your `pubspec.yaml`:

  ```yaml
  flutter:
    assets:
      - assets/translations/
  ```

  Then, you can load the translations using `Translations.byFile()`:

  ```dart
  extension MyTranslations on String {
    static final _t = Translations.byFile('en-US', dir: 'assets/translations');     
    String get i18n => localize(this, _t);  
  }
  ```

  The above code will asynchronously load all the translations from the `.json` files present in the `assets/translations` directory, and then rebuild your widgets with those new translations.

  Note: Since rebuilding widgets when the translations finish loading can cause a visible flicker, you can optionally avoid that by preloading the translations before running your app. To that end, first create a `load()` method in your `MyTranslations`  extension:

  ```dart
  extension MyTranslations on String {
    static final _t = Translations.byFile('en-US', dir: 'assets/translations');  
    String get i18n => localize(this, _t);  
    
    static Future<void> load() => _t.load(); // Here!  
  }
  ```

  And then, in your `main()` method, call `MyTranslations.load()` before running the app:

  ```dart
  void main() async {
    WidgetsFlutterBinding.ensureInitialized();
    
    await MyTranslations.load(); // Here!
    
    runApp(
      I18n(
        initialLocale: await I18n.loadLocale(),
        autoSaveLocale: true,
        child: AppCore(),
      ),
    );
  }
  ```

  Another alternative is using a `FutureBuilder`:

  ```dart
  return FutureBuilder(
    future: MyTranslations.load(),
    builder: (context, snapshot) {
      if (snapshot.connectionState == ConnectionState.done) {
      return MyWidget(...);
    } else {
      return const Center(child: CircularProgressIndicator());
    } ...
  ```       

  Try running
  the <a href="https://github.com/marcglasberg/i18n_extension/blob/master/example/lib/6_load_example/main.dart">
  load example</a>.
