### ISSUE TITLE
Did I forgot something?

### ISSUE THREAD

**Issue by BassamxMednini** [marcglasberg/i18n_extension#9]
Hi, I'm trying to translate a simple flutter application, but for some reason it doesn't work. 

**pubspec.yaml**
`i18n_extension: ^1.2.0`

**main.dart**
```
import 'package:i18n_extension/i18n_widget.dart';
import 'main.i18n.dart';
...
home: I18n(child: MyHomePage(),)
...
appBar: AppBar(title: Text("i18n Demo" .i18n))
```
**main.i18n.dart**
```
import 'package:i18n_extension/i18n_extension.dart';

extension Localization on String {
  static var t = Translations("en_us") +
      {
        "en_us": "i18n Demo1",
        "de": "KLAPPT?",
      };

  String get i18n => localize(this, t);

  String fill(List<Object> params) => localizeFill(this, params);

  String plural(int value) => localizePlural(value, this, t);

  String version(Object modifier) => localizeVersion(modifier, this, t);

  Map<String, String> allVersions() => localizeAllVersions(this, t);
}
```

**Result:** Nothing. There is no error message. However, the appbar title doesn't translate - neither in english nor in german.

**Comment by marcglasberg** [comment]
This is in the docs:

Don't ever put translatable strings in the same widget where you declared the I18n widget, since they may not respond to future locale changes. For example, this is a mistake:

```
Widget build(BuildContext context) {
  return I18n(
    child: Scaffold(
      appBar: AppBar(title: Text("Hello there".i18n)),
      body: MyScreen(),
  );
}
```

Please see if the above solves your problem, and let me know. If it doesn't solve your problem, you must post here a single file containing the whole code to demonstrate the problem, complete with a main method which I can run.

**Comment by BassamxMednini** [comment]
I copied now the **main.dart** and **main.18n.dart** file from the example and still nothing works. Instead I got now this message 

> flutter: ➜ Translation key in 'en_us' is missing: "i18n Demo".

**Comment by marcglasberg** [comment]
You set that the translation keys are in English:

```
static var t = Translations("en_us") +
```

And then the translation key is the text to which you appy .i18n:

```
AppBar(title: Text("i18n Demo".i18n))
```

In this case, the translation key is `"i18n Demo"`.

The error message means you haven't defined translations for this key. In your code I see you have defined this key:

```
"en_us": "i18n Demo1",
```

You should have used `"i18n Demo"` instead of `"i18n Demo1"`, like this:

```
"en_us": "i18n Demo",
```
